"""add foreign keys for product and category

Revision ID: e870caf59761
Revises: 0d60b330f169
Create Date: 2026-03-03 14:21:55.713718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e870caf59761'
down_revision: Union[str, Sequence[str], None] = '0d60b330f169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
  
    # Add user_id to categories and link to users
    with op.batch_alter_table('categories', recreate="always") as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_categories_user', 'users', ['user_id'], ['id'])
    
    # Products table
    with op.batch_alter_table('products', recreate="always") as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('category_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_foreign_key('fk_products_user', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('products', recreate="always") as batch_op:
        batch_op.drop_constraint('fk_products_user', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.alter_column('category_id', existing_type=sa.Integer(), nullable=True)
    
    with op.batch_alter_table('categories', recreate="always") as batch_op:
        batch_op.drop_constraint('fk_categories_user', type_='foreignkey')
        batch_op.drop_column('user_id')
